# Generated by Django 2.2.7 on 2019-11-14 12:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191114_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
