# Generated by Django 2.2.7 on 2019-11-14 12:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191114_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=None),
        ),
    ]
